# Generated by Django 5.2.4 on 2025-07-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_description_remove_book_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.PositiveBigIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
