# Generated by Django 5.2.4 on 2025-07-29 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
