# Generated by Django 5.2.4 on 2025-07-29 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_delete_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
