# Generated by Django 5.2.4 on 2025-07-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_order_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
