# Generated by Django 5.2.4 on 2025-07-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_order_user_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_order_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
