# Generated by Django 5.2.4 on 2025-07-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_order_user_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_order_number',
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
